// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type User struct {
	ID        string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Webhook struct {
	ID          string
	UserID      string
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Request struct {
	ID            string
	WebhookID     string
	Method        string
	Path          string
	QueryParams   string
	Headers       string
	Body          string
	ContentType   string
	SourceIP      string
	ContentLength int64
	CreatedAt     time.Time
}
