// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package sqlc

import (
	"context"
	"time"
)

const createRequest = `-- name: CreateRequest :exec
INSERT INTO requests (id, webhook_id, method, path, query_params, headers, body, content_type, source_ip, content_length, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRequestParams struct {
	ID            string
	WebhookID     string
	Method        string
	Path          string
	QueryParams   string
	Headers       string
	Body          string
	ContentType   string
	SourceIp      string
	ContentLength int64
	CreatedAt     time.Time
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) error {
	_, err := q.db.ExecContext(ctx, createRequest,
		arg.ID,
		arg.WebhookID,
		arg.Method,
		arg.Path,
		arg.QueryParams,
		arg.Headers,
		arg.Body,
		arg.ContentType,
		arg.SourceIp,
		arg.ContentLength,
		arg.CreatedAt,
	)
	return err
}

const deleteOldRequests = `-- name: DeleteOldRequests :exec
DELETE FROM requests
WHERE id IN (
  SELECT r.id FROM requests r
  WHERE r.webhook_id = ?
  ORDER BY r.created_at DESC
  LIMIT -1 OFFSET 100
)
`

func (q *Queries) DeleteOldRequests(ctx context.Context, webhookID string) error {
	_, err := q.db.ExecContext(ctx, deleteOldRequests, webhookID)
	return err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, webhook_id, method, path, query_params, headers, body, content_type, source_ip, content_length, created_at
FROM requests
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetRequestByID(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Method,
		&i.Path,
		&i.QueryParams,
		&i.Headers,
		&i.Body,
		&i.ContentType,
		&i.SourceIp,
		&i.ContentLength,
		&i.CreatedAt,
	)
	return i, err
}

const listRequestsByWebhookID = `-- name: ListRequestsByWebhookID :many
SELECT id, webhook_id, method, path, query_params, headers, body, content_type, source_ip, content_length, created_at
FROM requests
WHERE webhook_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListRequestsByWebhookIDParams struct {
	WebhookID string
	Limit     int64
}

func (q *Queries) ListRequestsByWebhookID(ctx context.Context, arg ListRequestsByWebhookIDParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByWebhookID, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Method,
			&i.Path,
			&i.QueryParams,
			&i.Headers,
			&i.Body,
			&i.ContentType,
			&i.SourceIp,
			&i.ContentLength,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
