// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: requests.sql

package sqlc

import (
	"context"
	"time"
)

const createRequest = `-- name: CreateRequest :exec
INSERT INTO requests (id, webhook_id, method, path, query_params, headers, body, content_type, source_ip, content_length, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`

type CreateRequestParams struct {
	ID            string
	WebhookID     string
	Method        string
	Path          string
	QueryParams   string
	Headers       string
	Body          string
	ContentType   string
	SourceIP      string
	ContentLength int64
	CreatedAt     time.Time
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) error {
	_, err := q.db.ExecContext(ctx, createRequest,
		arg.ID,
		arg.WebhookID,
		arg.Method,
		arg.Path,
		arg.QueryParams,
		arg.Headers,
		arg.Body,
		arg.ContentType,
		arg.SourceIP,
		arg.ContentLength,
		arg.CreatedAt,
	)
	return err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, webhook_id, method, path, query_params, headers, body, content_type, source_ip, content_length, created_at
FROM requests
WHERE id = ?
LIMIT 1`

func (q *Queries) GetRequestByID(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequestByID, id)
	var r Request
	err := row.Scan(
		&r.ID,
		&r.WebhookID,
		&r.Method,
		&r.Path,
		&r.QueryParams,
		&r.Headers,
		&r.Body,
		&r.ContentType,
		&r.SourceIP,
		&r.ContentLength,
		&r.CreatedAt,
	)
	return r, err
}

const listRequestsByWebhookID = `-- name: ListRequestsByWebhookID :many
SELECT id, webhook_id, method, path, query_params, headers, body, content_type, source_ip, content_length, created_at
FROM requests
WHERE webhook_id = ?
ORDER BY created_at DESC
LIMIT ?`

type ListRequestsByWebhookIDParams struct {
	WebhookID string
	Limit     int64
}

func (q *Queries) ListRequestsByWebhookID(ctx context.Context, arg ListRequestsByWebhookIDParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByWebhookID, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var requests []Request
	for rows.Next() {
		var r Request
		if err := rows.Scan(
			&r.ID,
			&r.WebhookID,
			&r.Method,
			&r.Path,
			&r.QueryParams,
			&r.Headers,
			&r.Body,
			&r.ContentType,
			&r.SourceIP,
			&r.ContentLength,
			&r.CreatedAt,
		); err != nil {
			return nil, err
		}
		requests = append(requests, r)
	}
	return requests, rows.Err()
}

const deleteOldRequests = `-- name: DeleteOldRequests :exec
DELETE FROM requests
WHERE webhook_id = ?
  AND id NOT IN (
    SELECT id FROM requests
    WHERE webhook_id = ?
    ORDER BY created_at DESC
    LIMIT 100
  )`

type DeleteOldRequestsParams struct {
	WebhookID      string
	WebhookIDInner string
}

func (q *Queries) DeleteOldRequests(ctx context.Context, arg DeleteOldRequestsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldRequests, arg.WebhookID, arg.WebhookIDInner)
	return err
}
