// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlc

import (
	"context"
	"time"
)

const createWebhook = `-- name: CreateWebhook :exec
INSERT INTO webhooks (id, user_id, name, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWebhookParams struct {
	ID          string
	UserID      string
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) error {
	_, err := q.db.ExecContext(ctx, createWebhook,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks
WHERE id = ?
`

func (q *Queries) DeleteWebhook(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, id)
	return err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, user_id, name, description, created_at, updated_at
FROM webhooks
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id string) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookRequestCount = `-- name: GetWebhookRequestCount :one
SELECT COUNT(*) FROM requests
WHERE webhook_id = ?
`

func (q *Queries) GetWebhookRequestCount(ctx context.Context, webhookID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWebhookRequestCount, webhookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listWebhooksByUserID = `-- name: ListWebhooksByUserID :many
SELECT id, user_id, name, description, created_at, updated_at
FROM webhooks
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksByUserID(ctx context.Context, userID string) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :exec
UPDATE webhooks
SET name = ?, description = ?, updated_at = ?
WHERE id = ?
`

type UpdateWebhookParams struct {
	Name        string
	Description string
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhook,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
